# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import isearch_pb2 as isearch__pb2


class HelloStub(object):
    """服务名及方法名
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.apiBridge = channel.unary_unary(
                '/isearch.Hello/apiBridge',
                request_serializer=isearch__pb2.req.SerializeToString,
                response_deserializer=isearch__pb2.res.FromString,
                )


class HelloServicer(object):
    """服务名及方法名
    """

    def apiBridge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HelloServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'apiBridge': grpc.unary_unary_rpc_method_handler(
                    servicer.apiBridge,
                    request_deserializer=isearch__pb2.req.FromString,
                    response_serializer=isearch__pb2.res.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'isearch.Hello', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Hello(object):
    """服务名及方法名
    """

    @staticmethod
    def apiBridge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/isearch.Hello/apiBridge',
            isearch__pb2.req.SerializeToString,
            isearch__pb2.res.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
